services:
  html-site:
    restart: always
    image: nginx:stable-alpine
    container_name: html-site
    volumes:
      - ./html-site/index.html:/usr/share/nginx/html/index.html
    ports:
      - 8080:80
    depends_on:
      - image-site

  image-site:
    restart: always
    image: nginx:stable-alpine
    container_name: image-site
    volumes:
      - ./image-site/default.conf:/etc/nginx/conf.d/default.conf
      - ./image-site/cat.jpeg:/usr/share/nginx/html/cat.jpeg
    ports:
      - 9090:80
