apiVersion: v1
kind: Service
metadata:
  name: fastapi-proxy
  labels:
    app: fastapi-proxy
    service: fastapi-proxy
spec:
  ports:
  - port: 80
    name: http
    targetPort: http
  selector:
    app: fastapi-proxy

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-proxy
  template:
    metadata:
      labels:
        app: fastapi-proxy
    spec:
      containers:
      - name: fastapi-proxy
        image: grs2docker2hub/istio-tracing-test01
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: fastapi-proxy-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
    - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fastapi-proxy-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - fastapi-proxy-gateway
  http:
  - match:
    - uri:
        prefix: /end/
    rewrite:
      uri: "/"
    route:
    - destination:
        host: fastapi-end
        port:
          number: 80
  - route:
    - destination:
        host: fastapi-proxy
        port:
          number: 80
